language: android

notifications:
  email: false

branches:
  except:
    - gh-pages

android:
  components:
    - build-tools-19.1.0
    - android-19
    - sysimg-19
  licenses:
    - android-sdk-license-5be876d5
    - '.*intel.+'

before_install:
  - curl https://raw.githubusercontent.com/embarkmobile/android-sdk-installer/master/wait_for_emulator >> wait.sh
  - chmod u+x wait.sh

  # Create and start emulator  
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  # Make sure the emulator has started before running tests
  - ./wait.sh
