language: android

notifications:
  email: false
  hipchat:
    rooms:
      secure: CO1rkQMD/T5fpAozqneRg6SqVIMrgi659A5hGUA9pdwFXDv9y4MZTjTE9cws30po1v74k9EtrNSGwAMnZoKao6lorQBL2d1S+HQKkFQIrwNJ1wLrgFz8KBDziv35Bt3+8yYHxPGtu0iLgK+xHvSx2WWs+MtoH9Xdj37QfJi56+o=

branches:
  except:
    - gh-pages

android:
  components:
    # Update these each time
    - platform-tools
    - tools

    - build-tools-20.0.0

    # Target SDK
    - android-20
    # For emulator
    - android-19
    - sys-img-armeabi-v7a-android-19

    # Local Maven Repos
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - android-sdk-preview-license-52d11cd2

before_install:
  - android list sdk --no-ui --all

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
 - ./gradlew clean build connectedCheck
