language: android

notifications:
  email: false
  hipchat:
    rooms:
      secure: CO1rkQMD/T5fpAozqneRg6SqVIMrgi659A5hGUA9pdwFXDv9y4MZTjTE9cws30po1v74k9EtrNSGwAMnZoKao6lorQBL2d1S+HQKkFQIrwNJ1wLrgFz8KBDziv35Bt3+8yYHxPGtu0iLgK+xHvSx2WWs+MtoH9Xdj37QfJi56+o=

branches:
  except:
    - gh-pages

#android:
#  components:
#    - build-tools-19.1.0
#  licenses:
#    - android-sdk-license-5be876d5

before_install:
  # workaround for https://github.com/travis-ci/travis-ci/issues/2279
  - 'sudo mv /usr/local/android-sdk/tools/android-* /usr/local/bin'
  # Accept all licenses (workaround for travis-ci/travis-ci#2466)
  # Upgrade 'platform-tools' before 'tools' (workaround for https://github.com/travis-ci/travis-ci/issues/2470)
  # Run dinstinct 'android update sdk' commands
  - "android-update-sdk --components='platform-tools,tools' --accept-licenses='.+'"
  - "android-update-sdk --components='build-tools-19.1.0' --accept-licenses='.+'"
  - "android-update-sdk --components='android-19' --accept-licenses='.+'"
  - "android-update-sdk --components='sys-img-armeabi-v7a-android-19' --accept-licenses='.+'"
  - "android-update-sdk --components='extra-android-m2repository,extra-google-m2repository' --accept-licenses='.+'"

  - curl https://raw.githubusercontent.com/embarkmobile/android-sdk-installer/master/wait_for_emulator >> wait.sh
  - chmod u+x wait.sh

  - android list sdk --no-ui --all --extended

  # Create and start emulator  
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  # Make sure the emulator has started before running tests
  - ./wait.sh
